### ISSUE TITLE
Refactor links hierarchy of the site, including documentation links

### ISSUE THREAD

**Issue by couet** [root-project/web#510]
**Suggestion by : Yaroslav Nikitenko**  https://github.com/ynikitenko

Today I searched for User's guide on the site, and wanted to share several ideas for improvement.

1) Remove duplicate links.
In modern Web Development it's appreciated that same content has only one link on the site, and a link is meaningful in itself (see Django guidelines).
For example: from the main page I can see a link to the documentation,
https://root.cern/d/documentation.html
If I delete the last part, I get
https://root.cern/d/
which is a) meaningless b) same as the main page.
The third link to that same page is
https://root.cern/d/index.html

Surprisingly, the link
https://root.cern/index.html
has different contents!

Probably there is little surprise that there exists the 2nd version of the site,
https://root.cern.ch/ (with its own index.html, and all these links).
I think there should be one canonical link, and other links should redirect to that.

2a) https://root.cern/d/documentation.html
should ideally become just
https://root.cern/documentation

2b) or all documentation should be put into one directory with a clearer name, like
https://root.cern/doc/
In that case the manual (and other docs) should also be in that directory, not at
https://root.cern/manual/

3a) User Guide is located at
https://root.cern/d/guides/users-guide.html
On parent path
https://root.cern/d/guides/
there is an automatic list of guides (which is better than nothing/forbidden), but it would be better if it was not automatic (had the same design as the other site).

3b) the same for
https://root.cern/doc/
(automatic list)

4) As I understand, the main page for documentation is
https://root.cern.ch/d/documentation.html
There is also
https://root.cern/doc/master/
these two pages should probably be one page.

5) Rearrange "Provide your feedback"
I think github issues should go before the Forum in the list of options (if there are really two ways), because one can see closed and open issues (on the Forum I found several complaints about the links, but it's not clear whether they are open or closed without opening them).

6) From the documentation page "A number of topical User Guides and Manuals for various components of the system." leads to
https://root.cern/get_started/
which, in turn, repeats description of some existing resources. Could you please refactor these two pages into one, trying to repeat as little information as possible?

7) On the page https://root.cern/about/
there is no link to the documentation. This is some other version of the site, not the version at https://root.cern/d/

8) I found this page using the search window,
https://root.cern/d/root-user-guides-and-manuals.html
I think this is a very good reference page for documentation. Could you link this from the main documentation overview page? (or just use this page instead of that)

**Comment by couet** [comment]
https://root.cern/d/ should not be taken into account. The new web site is https://root.cern . The "d" one is a backup of the old web site. We keep it for now in case some missing information need to be migrated from the old one to the new one. So , in this issue, all the comments about the "d" version should be ignored.

**Comment by ynikitenko** [comment]
About the previous comment: I think there are options to signalize that the site is outdated to users. For example, to move it to a specific domain where it's unavailable to general public. Or, probably easier, to make a big add (banner) on that site that that is outdated.

**Comment by ynikitenko** [comment]
I also wanted to say that the Reference guide is a bit hidden.
I think that instead of two links on the site "Get Started" and "Manual", there should be just one "Documentation".
I think it's not intuitive that the Reference (which is pretty important, IMHO) is available through Manual -> Other learning resources. I think they should be of the same level in the documentation (together with Get Started).
It's easier to search one page with the documentation for Beginners, Experienced users and Reference, than trying to guess where I can find the Reference through several small pages.

If Get Started button is important, it may still lead to a subsection on the main Documentation page. Maybe a good specialist could work on the site's usability?

**Comment by ynikitenko** [comment]
And one more thing: on the page https://root.cern/doc/master/ there is a section

> Other types of documentation:
    ROOT Introductory Course.
    A rich set of ROOT tutorials and code examples are offered to developers to exercise specific functionality.
    A general Users Guide is provided for a more in depth explanation of concepts and functionality available in the ROOT system.
    A number of topical User Guides and Manuals for various components of the system.

\- that doesn't include the Manual (which is said to be one of the main documents). 

I really think that there should be one main page for documentation.

**Comment by couet** [comment]
You aid :  "I also wanted to say that the Reference guide is a bit hidden." .... Well, the big huge icon on the new web site front page is not really "hidden"....

**Comment by ynikitenko** [comment]
You are right. However, I looked not from the main page https://root.cern/, but from some other page. Then in the top horizontal menu there are still "Get Started" and "Manual", but not "Documentation" or "Reference Guide".
I'm not sure that having the big buttons and menu items on the main page is worth it; but a good UI specialist could know it better. For me personally, I just become a bit distracted and don't look at all of them.

**Comment by couet** [comment]
Well ... We now hit the point "it is a matter of taste"... The current structure is the result of a long concertation between the ROOT team members, the users, some experts in documentation building etc ... And of course the previous ROOT web site was the starting point. So It does not come randomly from nowhere . We had many iterations.. It was a long process and the current version is very far from the one initially proposed. We can always imagine something different and surely other structures can also work. But we choose that one. I guess we will keep it.

**Comment by ynikitenko** [comment]
Fine, then you may add my report to the long list of user feedback :) As I understand, any good site is changed at some time.

Great that experts on documentation building worked on that. However, when I open sites like https://numpy.org/ or https://www.boost.org/ (which is about C++), I see clear links to "Documentation".

However, I can say that duplication of interfaces (like buttons and menu items "Get Started" and "Forum & Help") is rather widespread in ROOT, so maybe it's part of its philosophy. 

If you decide to keep it and if it's really based on some research and useful to the community, that's great. I just didn't know that and thought that that could be improved (I'm more used to Python documentation style now).

**Comment by couet** [comment]
Can I close this issue ?

**Comment by ynikitenko** [comment]
My opinion is in the long list of problems I reported about. About the button names in the menu - we've discussed that. But all other problems remain, and it looks weird that you open an issue and then close it without changing anything.

Also it's strange that there is an "appointed person", who takes care of the site or documentation, but has not made any comment here - maybe he should read that first, before you close?

I reread this issue now, and the "old site" is not more than half of issues mentioned here.

**Comment by couet** [comment]
> 1) Remove duplicate links.
> In modern Web Development it's appreciated that same content has only one link on the site, and a link is meaningful in itself (see Django guidelines).
> For example: from the main page I can see a link to the documentation,
> https://root.cern/d/documentation.html
> If I delete the last part, I get
> https://root.cern/d/
> which is a) meaningless b) same as the main page.
> The third link to that same page is
> https://root.cern/d/index.html

All the "d" URLS are the old web site. Keep for the time being but will disappear. You should browse from https://root.cern

 
> Surprisingly, the link
> https://root.cern/index.html
> has different contents!

All the "d" URLS are the old web site. Keep for the time being but will disappear. You should browse from https://root.cern


> Probably there is little surprise that there exists the 2nd version of the site,
> https://root.cern.ch/ (with its own index.html, and all these links).
> I think there should be one canonical link, and other links should redirect to that.
> 
> 2a) https://root.cern/d/documentation.html
> should ideally become just
> https://root.cern/documentation

All the "d" URLS are the old web site. Keep for the time being but will disappear. You should browse from https://root.cern


> 2b) or all documentation should be put into one directory with a clearer name, like
> https://root.cern/doc/
> In that case the manual (and other docs) should also be in that directory, not at
> https://root.cern/manual/

We will leave the documentation as it is. 
   - Reference Guide as basis
   - Manual For a global overview
   - Topical Manuals for special packages
   - Primer for beginners

> 3a) User Guide is located at
> https://root.cern/d/guides/users-guide.html
> On parent path
> https://root.cern/d/guides/
> there is an automatic list of guides (which is better than nothing/forbidden), but it would be better if it was not automatic (had the same design as the other site).

All the "d" URLS are the old web site. Keep for the time being but will disappear. You should browse from https://root.cern

The user's guide will be removed also (kept for the time being to cross check the information)

> 3b) the same for
> https://root.cern/doc/
> (automatic list)
> 
> 4) As I understand, the main page for documentation is
> https://root.cern.ch/d/documentation.html

No: All the "d" URLS are the old web site. Keep for the time being but will disappear. You should browse from https://root.cern


> There is also
> https://root.cern/doc/master/
> these two pages should probably be one page.

This is the Reference Guide.

> 5) Rearrange "Provide your feedback"
> I think github issues should go before the Forum in the list of options (if there are really two ways), because one can see closed and open issues (on the Forum I found several complaints about the links, but it's not clear whether they are open or closed without opening them).

In which page ?

> 6) From the documentation page "A number of topical User Guides and Manuals for various components of the system." leads to
> https://root.cern/get_started/
> which, in turn, repeats description of some existing resources. Could you please refactor these two pages into one, trying to repeat as little information as possible?

Which documentation page are you talking about ?


> 7) On the page https://root.cern/about/
> there is no link to the documentation. This is some other version of the site, not the version at https://root.cern/d/

"About" is meant to expose the context, the history, etc ....

 
> 8) I found this page using the search window,
> https://root.cern/d/root-user-guides-and-manuals.html
> I think this is a very good reference page for documentation. Could you link this from the main documentation overview page? (or just use this page instead of that)

This is the User's Guide. we already discussed that.

**Comment by eguiraud** [comment]
Hi,
we should probably add a banner to `root.cern/d` that tells users that they are looking at old, possibly deprecated pages

**Comment by couet** [comment]
Yes that would be the best. I am not sure that's easy to do, though...

**Comment by ynikitenko** [comment]
> > 1. Rearrange "Provide your feedback"
> >    I think github issues should go before the Forum in the list of options (if there are really two ways), because one can see closed and open issues (on the Forum I found several complaints about the links, but it's not clear whether they are open or closed without opening them).
> 
> In which page ?

https://root.cern/doc/master/

**Comment by ynikitenko** [comment]
> > 1. From the documentation page "A number of topical User Guides and Manuals for various components of the system." leads to
> >    https://root.cern/get_started/
> >    which, in turn, repeats description of some existing resources. Could you please refactor these two pages into one, trying to repeat as little information as possible?
> 
> Which documentation page are you talking about ?

https://root.cern/doc/master/

You see, we can't even be sure about the "documentation page" we discuss. I really think that there should be only one "documentation page", probably with a title "Documentation", a menu item "Documentation" and a link like root.cern/documentation, or just root.cern/doc.

**Comment by couet** [comment]
and it should be GitHub issue ... not Jira... thanks for pointing

**Comment by couet** [comment]
We do not have the name "Documentation" we have: Reference Guide, Manual, Topical, and Primer ... so when you say "Documentation" it could be any of those. And it will stay like that.

**Comment by eguiraud** [comment]
> and it should be GitHub issue ... not Jira... thanks for pointing

ah, I was just fixing that also prompted by this discussion: https://github.com/root-project/root/pull/7334

**Comment by ynikitenko** [comment]
> > 2b) or all documentation should be put into one directory with a clearer name, like
> > https://root.cern/doc/
> > In that case the manual (and other docs) should also be in that directory, not at
> > https://root.cern/manual/
> 
> We will leave the documentation as it is.

I'm not saying about documentation resources. I'm speaking about the link hierarchy on the site.

The link is what you see in the address bar in the browser. The link hierarchy means that root.cern is the main page, and root.cern/docs is the parent of all documentation, and other folders are parents to their topics. It is good for navigation when your links form a hierarchy. For some people that is important and easy to use. When your document is root.cern/manual, this is not a hierarchy. A hierarchical (and I'd say natural) organization is when the manual is in the documentation section (root.cern/doc/manual). From that link you can go one step above and get all documenation (root.cern/doc). This is very fast with a keyboard, you just edit your address line. And this is easy to understand. For me it's much easier to understand a structure than a group of semantically unrelated links. It is also considered a good practice on the web (if I remember correctly from Django tutorials).

**Comment by couet** [comment]
> ah, I was just fixing that also prompted by this discussion: root-project/root#7334

Ah ok, may be you can also change the order in that case as suggested by @ynikitenko ?

**Comment by ynikitenko** [comment]
I can also see that your current site includes the old site in search results.
For example, I type "documentation" in the search box from root.cern, and I get the 6th link
https://www.google.com/url?client=internal-element-cse&cx=002589152045094483918:maus8l2p5om&q=https://root.cern/d/documentation.html&sa=U&ved=2ahUKEwjOmtXK7JHvAhVn-SoKHfKaABAQFjAFegQIBhAB&usg=AOvVaw1dmwnCJmN9GnftZxy-hTQc
(which leads to the old site, https://root.cern/d/documentation.html).

I think that the best technical way is just to remove the old site from the link hierarchy.
1) Create a subdomain old.root.cern, and serve all old content you might need from there.
a) make it password protected so that only your team can access that, or
b) create a large deprecation banner that that site is old (which is almost done).
2) Prohibit search engines to index that site (just add that to robots.txt)
3) Redirect all pages on root.cern/d to root.cern (this might not be straightforward, but still possible). It is trivial to change the server configuration (I use nginx, but I think Apache allows that easily too). The only hitch may be that you renamed some links, but there are probably just a few of such links.

Without that Google and other search engines will never know that root.cern/d is your old site, and not a legitimate part of root.cern (maybe there are developer instruments in Google for that; but anyway that's just one search engine).

I can also see that you didn't mention the old site in https://root.cern/robots.txt. I think that is fine, and it would be better to redirect all links to the new site. Maybe it would bring some of its SEO weight to the new site. 

I read your argument that "it may not be easy". It is not difficult if someone has already created that site. Anyway I'm not saying whether it's difficult or not. Maybe some of the ROOT team may volunteer on that? Otherwise you'll still have to solve the problems I mentioned (unless the old site will be deleted really soon and you don't care at all about SEO).

**Comment by couet** [comment]
We know we have to work on the search engine. But we will keep the new site as it is. I can only say (once more) that the new site is the result of a long concertation in the ROOT team and with users. We had many prototypes ...

**Comment by Axel-Naumann** [comment]
> I can also see that you didn't mention the old site in https://root.cern/robots.txt.

Good point, I think we should!

We keep `/d` to find relevant content that we miss in the new site. @couet told me that this year he will migrate content that we found was missing so we can then turn off `/d`. Even more of a reason to hide it from search engines.

I think it's very good to discuss these things; we need to see whether changes are worth the effort, i.e. what are the benefits, and how certain can we be that the view that the change is progress is shared. If that's clear, and if we don't break tons of links, then changing is certainly always an option. That's why we have git controlled web sources these days! :-) I *think* what @couet is referring to is the separation of a manual and the reference guide; that's indeed something fairly fundamental.

I will implement the change to `robots.txt` unless there are objections?

**Comment by couet** [comment]
> I think what @couet is referring to is the separation of a manual and the reference guide; that's indeed something fairly > > fundamental. 
Yes exactly, and at the end the removal of the user's guide with we keep right now fro the same reason we keep the `/d` web site.

**Comment by ynikitenko** [comment]
About the User's Guide: maybe it should not be deleted, but just marked as historical? This is a very good document to read (apart from numerous typos), and a very detailed one on some issues.

**Comment by Axel-Naumann** [comment]
OTOH much of it is outdated / uses paths that we don't recommend taking anymore, and for most users who'd read the users' guide it's impossible to tell. So in our estimate it does more harm than good.

**Comment by Axel-Naumann** [comment]
> I will implement the change to robots.txt unless there are objections?

Done. Let's see.

**Comment by ynikitenko** [comment]
> uses paths that we don't recommend taking anymore

For me it reflects ROOT philosophy (as I understood that when I read User's Guide a long time ago). But if that has changed, then I agree it'd be best to avoid that (and copy the good parts to some other places, if that was not already done). 

But I think it's not enough to only remove old documentation. All these methods and classes are still present.

I found a list of deprecations at https://root.cern/doc/master/deprecated.html . As I understand, ROOT 7 will have a rather different design. So probably this list of deprecations should be much larger? I'm very much interested in changes, because I want my code to work both for ROOT 6 and ROOT 7 in the future.

(this could be made into a separate feature request. No such issue exists yet)

**Comment by Axel-Naumann** [comment]
We only deprecate things for which we have a production-grade replacement. That takes a while - so we often don't deprecate things even though we recommend against them. But this will become more and more, indeed.

**Comment by ynikitenko** [comment]
Other outdated links were mentioned here in comments.
https://github.com/root-project/web/issues/511#issuecomment-788930896

**Comment by Axel-Naumann** [comment]
The htmldoc subdirectory is now hidden, Google will forget about it. I expect all existing links to vanish by us removing /d/.

**Comment by ynikitenko** [comment]
As I understand, you closed that path, because when I try to get TSpectrum documentation from root.cern/root, it is forbidden (https://github.com/root-project/web/issues/542).
Generally, if the link existed, it's much better to make a redirect than to just close or remove that.
Maybe the issue with root.cern should be made a separate one.

**Comment by couet** [comment]
I guess this long discussion can be closed now.
